name: Code Quality Flow
description: Workflow for code review, refactoring, and quality improvement
type: quality
project_type: maintenance

steps:
  - step: 1
    name: "Code Review"
    agent: code-reviewer
    inputs:
      - code_to_review
      - existing_patterns
    outputs:
      - review-report.json
      - issues_identified

  - step: 2
    name: "Refactoring Analysis"
    agent: refactoring-specialist
    inputs:
      - review-report.json (from step 1)
      - codebase
    outputs:
      - refactor-plan.json
      - priority_list

  - step: 3
    name: "Compliance Audit"
    agent: compliance-auditor
    inputs:
      - codebase
      - review-report.json (from step 1)
    outputs:
      - compliance-report.json
      - violations_list

  - step: 4
    name: "Quality Validation"
    agent: qa
    inputs:
      - refactor-plan.json (from step 2)
      - compliance-report.json (from step 3)
    outputs:
      - quality_gate_decision.json
      - recommendations

completion_criteria:
  - All critical issues addressed
  - Compliance violations resolved
  - Code quality metrics improved
  - Documentation updated

triggers:
  keywords:
    - code quality
    - code review
    - refactor
    - tech debt
    - code smell
    - clean up
