name: Quick Flow Development Workflow
description: Fast-track workflow for bug fixes, small features, and minor enhancements
type: quick
project_type: enhancement

# NOTE: The triggers section below is for documentation only.
# The actual workflow selection uses keywords from .opencode/config.yaml workflow_selection section.
# See .opencode/config.yaml for the authoritative keyword list used by the routing system.

# Quick Flow: Planner → Developer → QA (minimal overhead)
# Use for: Bug fixes, hotfixes, small features, documentation updates, refactoring

steps:
  - step: 0
    name: 'Planning Phase'
    agent: planner
    inputs:
      - user_requirements
      - existing_codebase
    outputs:
      - plan-{{workflow_id}}.md
      - plan-{{workflow_id}}.json
      - reasoning: .opencode/context/history/reasoning/{{workflow_id}}/00-planner.json
    validation:
      schema: .opencode/schema/plan.schema.json
      gate: .opencode/context/history/gates/{{workflow_id}}/00-planner.json
    description: |
      Quick planning for bug fixes and small features:
      - Analyze requirements and scope
      - Create focused plan for quick implementation
      - Validate plan feasibility

  - step: 1
    name: 'Implementation'
    agent: developer
    inputs:
      - plan-{{workflow_id}}.json (from step 0)
      - user_requirements
      - existing_codebase
    outputs:
      - dev-manifest-{{workflow_id}}.json
      - code-artifacts
      - reasoning: .opencode/context/history/reasoning/{{workflow_id}}/01-developer.json
    validation:
      schema: .opencode/schema/artifact_manifest.schema.json
      gate: .opencode/context/history/gates/{{workflow_id}}/01-developer.json

  - step: 2
    name: 'Quality Validation'
    agent: qa
    inputs:
      - plan-{{workflow_id}}.json (from step 0)
      - dev-manifest-{{workflow_id}}.json (from step 1)
      - code-artifacts (from step 1)
    outputs:
      - quality-report-{{workflow_id}}.json
      - test-results-{{workflow_id}}.json
      - reasoning: .opencode/context/history/reasoning/{{workflow_id}}/02-qa.json
    validation:
      schema: .opencode/schema/quality-report.schema.json
      gate: .opencode/context/history/gates/{{workflow_id}}/02-qa.json

completion_criteria:
  - Implementation validated against requirements
  - Tests passing
  - Code quality acceptable
  - No critical security issues

triggers:
  keywords:
    - bug fix
    - hotfix
    - quick fix
    - small feature
    - documentation
    - refactor
    - minor change
  file_changes: <5
  estimated_time: <4 hours

skip_agents:
  - analyst
  - pm
  - ux-expert
  - architect
