# Security Policies Configuration
# Enterprise-grade security controls for tool execution and data handling

# ==============================================================================
# Bash Command Security Policies
# ==============================================================================

bash_security:
  # Critical: Commands that MUST be blocked
  critical_blocks:
    - pattern: "^rm\\s+-rf\\s+/"
      severity: "critical"
      reason: "Prevents system destruction"
      block: true
      alert: true

    - pattern: "^rm\\s+-rf\\s+\\*"
      severity: "critical"
      reason: "Prevents mass deletion"
      block: true
      alert: true

    - pattern: "(format|mkfs|fdisk|parted)\\s+"
      severity: "critical"
      reason: "Prevents disk formatting"
      block: true
      alert: true

    - pattern: "dd\\s+(if|of)="
      severity: "critical"
      reason: "Prevents low-level disk operations"
      block: true
      alert: true

    - pattern: ":\\(\\)\\{\\s*:\\|:\\&\\s*\\};:"
      severity: "critical"
      reason: "Prevents fork bomb attacks"
      block: true
      alert: true

    - pattern: "curl.*\\|.*bash"
      severity: "critical"
      reason: "Prevents remote code execution"
      block: true
      alert: true

    - pattern: "wget.*&&.*(bash|sh|python)"
      severity: "critical"
      reason: "Prevents remote code execution"
      block: true
      alert: true

    - pattern: ">(\\s*)/dev/(sd|hd|nvme)"
      severity: "critical"
      reason: "Prevents direct device writes"
      block: true
      alert: true

  # High risk: Commands requiring approval
  high_risk_commands:
    - pattern: "git\\s+push\\s+(--force|-f)"
      severity: "high"
      reason: "Force push can overwrite history"
      require_approval: true
      approval_message: "Force push detected. This will rewrite remote history. Continue?"

    - pattern: "docker\\s+(rm|rmi|prune).*(-f|--force)"
      severity: "high"
      reason: "Forced container/image deletion"
      require_approval: true

    - pattern: "(npm|yarn|pnpm)\\s+(publish|deprecate)"
      severity: "high"
      reason: "Package publishing affects public registry"
      require_approval: true

    - pattern: "sudo\\s+"
      severity: "high"
      reason: "Elevated privileges"
      require_approval: true

    - pattern: "chmod\\s+777"
      severity: "high"
      reason: "Dangerous file permissions"
      require_approval: true
      approval_message: "Setting 777 permissions is a security risk. Continue?"

  # Medium risk: Commands requiring logging
  medium_risk_commands:
    - pattern: "git\\s+(commit|push)"
      severity: "medium"
      reason: "Version control operations"
      log: true
      notify_user: true

    - pattern: "(npm|yarn|pnpm)\\s+(install|update)"
      severity: "medium"
      reason: "Dependency modifications"
      log: true
      notify_user: true

    - pattern: "docker\\s+(build|run|exec)"
      severity: "medium"
      reason: "Container operations"
      log: true

  # Allowed patterns (whitelist for safe operations)
  safe_commands:
    - "git\\s+(status|diff|log|branch|show)"
    - "(npm|pnpm|yarn)\\s+(run|test|build)"
    - "ls\\s+"
    - "cat\\s+"
    - "grep\\s+"
    - "find\\s+"
    - "echo\\s+"
    - "pwd"
    - "cd\\s+"
    - "mkdir\\s+-p"
    - "touch\\s+"
    - "mv\\s+"  # Allow moves but log them
    - "cp\\s+"  # Allow copies but log them

  # Timeout enforcement
  timeouts:
    default_ms: 120000      # 2 minutes
    max_ms: 600000          # 10 minutes
    test_commands_ms: 300000  # 5 minutes for tests
    build_commands_ms: 600000 # 10 minutes for builds

  # Resource limits (ulimit integration)
  resource_limits:
    enabled: true
    max_cpu_seconds: 600    # 10 minutes CPU time
    max_memory_mb: 4096     # 4GB RAM
    max_file_descriptors: 1024
    max_processes: 512

# ==============================================================================
# File Operation Security Policies
# ==============================================================================

file_security:
  # Path validation (prevent directory traversal)
  path_validation:
    block_patterns:
      - pattern: "\\.\\./\\.\\./"
        reason: "Directory traversal attack"

      - pattern: "%2e%2e%2f"
        reason: "URL-encoded traversal attack"

      - pattern: "\\.\\.\\\\\\.\\.\\\\

"
        reason: "Windows path traversal"

      - pattern: "/etc/passwd"
        reason: "System file access"

      - pattern: "/etc/shadow"
        reason: "System password file"

    blocked_directories:
      - path: "/etc/**"
        reason: "System configuration files"
        exception_for_read: false

      - path: "/sys/**"
        reason: "System interface"
        exception_for_read: true  # Read-only allowed

      - path: "/proc/**"
        reason: "Process information"
        exception_for_read: true  # Read-only allowed

      - path: "/dev/**"
        reason: "Device files"
        exception_for_read: false

      - path: "~/.ssh/**"
        reason: "SSH private keys"
        exception_for_read: false

      - path: "~/.aws/**"
        reason: "AWS credentials"
        exception_for_read: false

      - path: "~/.config/gcloud/**"
        reason: "GCloud credentials"
        exception_for_read: false

      - path: "**/node_modules/**"
        reason: "Generated dependencies (should not edit)"
        exception_for_read: true

      - path: "**/.git/**"
        reason: "Git internals (use git commands)"
        exception_for_read: true

  # Sensitive file patterns
  sensitive_files:
    blocked_for_write:
      - pattern: "\\.env(\\..*)?$"
        reason: "Environment secrets"

      - pattern: "secrets/.*"
        reason: "Secrets directory"

      - pattern: ".*\\.key$"
        reason: "Private keys"

      - pattern: ".*\\.pem$"
        reason: "Certificates"

      - pattern: "credentials\\.json"
        reason: "Service account credentials"

      - pattern: "config\\.yaml.*password.*"
        reason: "Configuration with passwords"

    require_approval_for_write:
      - pattern: "package\\.json$"
        reason: "Dependency changes"

      - pattern: "package-lock\\.json$"
        reason: "Dependency lock file"

      - pattern: "Dockerfile$"
        reason: "Container configuration"

      - pattern: "docker-compose\\.ya?ml$"
        reason: "Container orchestration"

      - pattern: "\\.github/workflows/.*\\.ya?ml$"
        reason: "CI/CD pipeline"

      - pattern: "terraform/.*\\.tf$"
        reason: "Infrastructure as code"

  # File size limits
  size_limits:
    max_file_size_mb: 10
    max_read_file_size_mb: 100  # Can read larger files
    warn_above_mb: 5
    block_binary_files_above_mb: 1

  # Content validation
  content_validation:
    scan_for_secrets:
      enabled: true
      patterns:
        - name: "AWS Access Key"
          regex: "AKIA[0-9A-Z]{16}"

        - name: "AWS Secret Key"
          regex: "[0-9a-zA-Z/+]{40}"

        - name: "GitHub Token"
          regex: "ghp_[0-9a-zA-Z]{36}"

        - name: "Anthropic API Key"
          regex: "sk-ant-[0-9a-zA-Z-]+"

        - name: "Private Key"
          regex: "-----BEGIN (RSA |EC |OPENSSH )?PRIVATE KEY-----"

        - name: "Password in Code"
          regex: "(password|passwd|pwd)\\s*=\\s*['\"][^'\"]{8,}['\"]"

      action_on_detection: "block"
      notify_security_team: true

# ==============================================================================
# PII Detection & Redaction
# ==============================================================================

pii_protection:
  enabled: true

  # PII patterns
  patterns:
    - name: "Email Address"
      regex: "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}"
      redact_with: "[EMAIL_REDACTED]"
      log_detection: true

    - name: "SSN"
      regex: "\\b\\d{3}-\\d{2}-\\d{4}\\b"
      redact_with: "[SSN_REDACTED]"
      log_detection: true
      severity: "high"

    - name: "Credit Card"
      regex: "\\b(?:\\d{4}[- ]?){3}\\d{4}\\b"
      redact_with: "[CC_REDACTED]"
      log_detection: true
      severity: "high"

    - name: "Phone Number"
      regex: "\\b\\d{3}[-.]?\\d{3}[-.]?\\d{4}\\b"
      redact_with: "[PHONE_REDACTED]"
      log_detection: true

    - name: "IP Address"
      regex: "\\b(?:\\d{1,3}\\.){3}\\d{1,3}\\b"
      redact_with: "[IP_REDACTED]"
      log_detection: false  # Too common, noisy

  # Redaction strategy
  redaction:
    auto_redact_in_logs: true
    auto_redact_in_outputs: false  # May break functionality
    alert_on_detection: true
    require_approval_to_proceed: true

# ==============================================================================
# Web Access Security
# ==============================================================================

web_security:
  # Domain filtering
  allowed_domains:
    - "*.anthropic.com"
    - "*.github.com"
    - "*.npmjs.com"
    - "*.stackoverflow.com"
    - "*.wikipedia.org"
    - "docs.*.com"
    - "*.readthedocs.io"

  blocked_domains:
    - "*.onion"           # Tor
    - "*.i2p"             # I2P
    - "localhost"         # Local
    - "127.0.0.1"         # Loopback
    - "0.0.0.0"           # Wildcard
    - "192.168.*.*"       # Private network
    - "10.*.*.*"          # Private network
    - "172.16.*.*"        # Private network
    - "*.local"           # mDNS

  # Rate limiting
  rate_limits:
    max_fetches_per_minute: 10
    max_fetches_per_hour: 50
    max_fetches_per_day: 200

  # Content security
  content_security:
    max_response_size_mb: 10
    timeout_seconds: 30
    follow_redirects: true
    max_redirects: 5
    validate_ssl: true
    block_executables: true

# ==============================================================================
# MCP Server Security
# ==============================================================================

mcp_security:
  # Server allowlist
  allowed_servers:
    - name: "repo"
      trust_level: "high"
      tools: "*"

    - name: "artifacts"
      trust_level: "high"
      tools: "*"

    - name: "github"
      trust_level: "medium"
      tools: ["search", "read"]

    - name: "linear"
      trust_level: "medium"
      tools: ["search", "read"]

  # Blocked servers (security concerns)
  blocked_servers:
    - "untrusted-*"
    - "dev-*"  # Development servers not in production

  # Tool invocation security
  tool_security:
    require_allowlist: true
    audit_all_invocations: true
    timeout_seconds: 60
    max_invocations_per_minute: 20

# ==============================================================================
# Audit & Logging
# ==============================================================================

audit:
  enabled: true
  log_location: ".claude/context/audit/security.log"
  log_format: "json"

  # What to log
  log_events:
    - "security_violation"
    - "approval_required"
    - "approval_granted"
    - "approval_denied"
    - "blocked_command"
    - "sensitive_file_access"
    - "pii_detected"
    - "secret_detected"

  # Log retention
  retention:
    security_logs_days: 90
    audit_logs_days: 365
    compliance_logs_days: 2555  # 7 years

  # SIEM integration
  siem:
    enabled: false  # Set to true for production
    endpoint: "https://siem.example.com/api/events"
    api_key_env_var: "SIEM_API_KEY"
    batch_size: 100
    flush_interval_seconds: 60

# ==============================================================================
# Compliance & Reporting
# ==============================================================================

compliance:
  # SOC 2 Type II
  soc2:
    enabled: true
    requirements:
      - "Audit logging for all security events"
      - "PII detection and protection"
      - "Access control enforcement"
      - "Security incident response"

  # HIPAA (if handling health data)
  hipaa:
    enabled: false
    requirements:
      - "Encryption at rest and in transit"
      - "Access audit trails"
      - "PII/PHI redaction"
      - "Minimum necessary access"

  # GDPR (if handling EU data)
  gdpr:
    enabled: false
    requirements:
      - "Right to erasure support"
      - "Data minimization"
      - "Purpose limitation"
      - "PII detection and handling"

  # Reporting
  reporting:
    generate_monthly_reports: true
    report_location: ".claude/context/compliance/reports/"
    include_metrics:
      - "Security violations count"
      - "Approval requests and responses"
      - "PII detections"
      - "Blocked commands"
      - "Risk level distribution"

# ==============================================================================
# Incident Response
# ==============================================================================

incident_response:
  # Automatic responses
  auto_responses:
    critical_violation:
      - "Block operation immediately"
      - "Log full context"
      - "Alert security team"
      - "Suspend agent if pattern repeats"

    high_severity:
      - "Block operation"
      - "Log context"
      - "Require manual review"

    medium_severity:
      - "Require approval"
      - "Log event"
      - "Continue monitoring"

  # Notification channels
  notifications:
    slack_webhook: null  # Set for production
    email_addresses: []  # Set for production
    pagerduty_key: null  # Set for critical alerts

  # Escalation
  escalation:
    critical_threshold_per_hour: 3
    high_threshold_per_hour: 10
    auto_suspend_agent: true
    require_security_review: true
