name: summarize-and-publish
trigger: PostToolUse
priority: high
steps:
  - action: summarize_changes
    options:
      include_tests: true
      include_commands: true
  - action: publish_artifact
    options:
      destination: artifact-pane
      visibility: project
      notify:
        - cursor
        - factory
  - action: run_commands
    options:
      commands:
        - pnpm lint
        - pnpm test --watch=false
      stop_on_failure: true
