name: streaming-monitor
trigger: PostToolUse
priority: medium
description: Monitors fine-grained tool streaming performance and handles invalid JSON

conditions:
  - streaming_enabled: true
  - fine_grained_streaming: true

steps:
  - action: validate_tool_output
    options:
      check_json_validity: true
      handle_incomplete: true
      log_level: info

  - action: handle_invalid_json
    options:
      when: json_invalid
      wrapper_key: INVALID_JSON
      retry_strategy: exponential_backoff
      max_retries: 2
      notify_user: true
      log_to: .claude/context/streaming-errors.log

  - action: track_streaming_metrics
    options:
      metrics:
        - latency_reduction
        - chunk_count
        - parameter_size
        - completion_time
      store_in: .claude/context/streaming-metrics.json
      alert_thresholds:
        latency_ms: 5000
        incomplete_json_rate: 0.05

  - action: optimize_streaming
    options:
      auto_adjust_buffer: true
      learn_from_patterns: true
      suggestions:
        - reduce_parameter_size
        - increase_max_tokens
        - split_large_params

monitoring:
  success_criteria:
    - json_valid: true
    - latency_reduction: ">30%"
    - no_data_loss: true

  failure_actions:
    - log_error: true
    - notify_orchestrator: true
    - fallback_to_buffered: true

optimization:
  adaptive_chunking: true
  context_aware_buffering: true
  learn_agent_patterns: true
