name: publish-summary
trigger: after_run
description: Post-execution artifact publishing and quality reporting
steps:
  # Coverage: Generate test coverage report
  - command: pnpm coverage
    continue_on_fail: true

  # Quality: Run full lint and test suite
  - command: pnpm lint
    continue_on_fail: true

  - command: pnpm test --watch=false
    continue_on_fail: true

  # Artifact Publishing: Upload reports to Claude Project
  - upload:
      path: reports/
      destination: claude-project

  # Artifact Publishing: Upload spec documents to Claude Project
  - upload:
      path: .factory/docs/
      destination: claude-project

  # Notification: Alert team via Slack
  - notify:
      channel: slack
      template: 'Droid run {{run_id}} completed. Coverage: {{coverage}}%. Tests: {{test_status}}. Lint: {{lint_status}}.'

  # Summary: Note about context sync
  - note: 'Artifacts published to Claude Project. Manually sync to .cursor/context/ and .claude/context/artifacts/ if needed for cross-platform context.'
