name: checkpoint-guard
trigger: before_run
description: Pre-execution validation and security checks
steps:
  # Code Quality: Run linting before changes
  - command: pnpm lint
    abort_on_fail: true
  
  # Testing: Verify existing tests pass
  - command: pnpm test --watch=false
    abort_on_fail: true
  
  # Context: Note about attaching artifacts
  - note: 'Attach latest Cursor plan (.cursor/plans/latest.md) and Claude artifacts (.claude/context/artifacts/*) before execution for context.'
  
  # Security: Note about dangerous commands
  - note: 'Security: Dangerous commands (rm -rf, sudo rm, format, dd, mkfs) are blocked by Droid Shield. Use with caution.'
