name: Quick Flow Development Workflow
description: Fast-track workflow for bug fixes, small features, and minor enhancements
type: quick
project_type: enhancement
publish_policy: auto-on-pass # Automatically publish artifacts after validation passes

# Error Recovery Configuration
recovery:
  enabled: true
  checkpoint_dir: '.claude/context/runtime/runs/{{run_id}}/checkpoints'

retry_config:
  max_attempts: 3
  backoff_strategy: exponential
  initial_delay_ms: 1000
  retryable_errors: [timeout, network_error, rate_limit]

fallback_agents:
  developer: [code-reviewer, qa]
  architect: [developer, security-architect]
  qa: [developer, code-reviewer]
  planner: [architect, pm]
  code-reviewer: [developer, security-architect]
  security-architect: [code-reviewer, qa]

# NOTE: The triggers section below is for documentation only.
# The actual workflow selection uses keywords from .claude/config.yaml workflow_selection section.
# See .claude/config.yaml for the authoritative keyword list used by the routing system.

# Quick Flow: Developer → QA (minimal overhead)
# Use for: Bug fixes, hotfixes, small features, documentation updates, refactoring

steps:
  - step: 0
    name: 'Planning Phase'
    agent: planner
    inputs:
      - user_requirements
      - existing_codebase
    outputs:
      - plan-{{workflow_id}}.md
      - plan-{{workflow_id}}.json
      - reasoning: .claude/context/history/reasoning/{{workflow_id}}/00-planner.json
    validation:
      schema: .claude/schemas/plan.schema.json
      gate: .claude/context/history/gates/{{workflow_id}}/00-planner.json
    description: |
      Quick planning for bug fixes and small features:
      - Analyze requirements and scope
      - Create focused plan for quick implementation
      - Validate plan feasibility
      - **Publishing**: After validation, use `artifact-publisher` skill to publish plan artifacts to project feed

  - step: 0.1
    name: 'Plan Rating Gate'
    agent: orchestrator
    type: validation
    skill: response-rater
    provider_config: .claude/config/response-rater.yaml
    inputs:
      - plan-{{workflow_id}}.json (from step 0)
    outputs:
      - .claude/context/runtime/runs/{{run_id}}/plans/{{plan_id}}-rating.json
      - reasoning: .claude/context/history/reasoning/{{workflow_id}}/00.1-orchestrator.json
    validation:
      minimum_score: 7
      rubric_file: .claude/context/artifacts/standard-plan-rubric.json
      schema: .claude/schemas/plan-rating.schema.json
      gate: .claude/context/history/gates/{{workflow_id}}/00.1-orchestrator.json
    retry:
      max_attempts: 3
      on_failure: escalate_to_human
    timeout_escalation:
      enabled: true
      use_cache_on_timeout: true
    description: |
      Rate plan quality using response-rater skill.
      - Rubric: completeness, feasibility, risk mitigation, agent coverage, integration
      - Minimum passing score: 7/10
      - Providers: Auto-selected based on workflow type (quick-flow → standard tier: claude, gemini)
      - Timeout: 180s per provider, 600s total max
      - Fallback: Use cached rating if all providers timeout
      - If score < 7: Return to Planner with feedback, request improvements, re-rate
      - If score >= 7: Proceed with workflow execution

  - step: 1
    name: 'Implementation'
    agent: developer
    inputs:
      - plan-{{workflow_id}}.json (from step 0)
      - user_requirements
      - existing_codebase
    outputs:
      - dev-manifest.json
      - code-artifacts
      - reasoning: .claude/context/history/reasoning/{{workflow_id}}/01-developer.json
    validation:
      schema: .claude/schemas/artifact_manifest.schema.json
      gate: .claude/context/history/gates/{{workflow_id}}/01-developer.json
    description: |
      Implement bug fix or small feature:
      - Write code following plan
      - Create dev-manifest.json with file list
      - **Publishing**: After validation, use `artifact-publisher` skill to publish final implementation artifacts

  - step: 1.5
    name: 'Security Review (Conditional)'
    agent: security-architect
    condition: 'plan matches security keywords (auth, encrypt, secret, token, password, vulnerability, exploit)'
    inputs:
      - plan-{{workflow_id}}.json (from step 0)
      - dev-manifest.json (from step 1)
      - code-artifacts (from step 1)
    outputs:
      - security-review-{{workflow_id}}.json
      - reasoning: .claude/context/history/reasoning/{{workflow_id}}/01.5-security-architect.json
    validation:
      schema: .claude/schemas/security-review.schema.json
      gate: .claude/context/history/gates/{{workflow_id}}/01.5-security-architect.json
    description: |
      Conditional security review for security-sensitive changes:
      - Only executes if task matches security keywords
      - Review authentication and authorization changes
      - Check for security vulnerabilities
      - Validate secrets management and encryption
      - Review input validation and sanitization
      - Verify secure coding practices
      - Block merge if critical security issues found

  - step: 2
    name: 'Code Review'
    agent: code-reviewer
    inputs:
      - plan-{{workflow_id}}.json (from step 0)
      - dev-manifest.json (from step 1)
      - code-artifacts (from step 1)
    outputs:
      - code-review-{{workflow_id}}.json
      - reasoning: .claude/context/history/reasoning/{{workflow_id}}/02-code-reviewer.json
    validation:
      schema: .claude/schemas/code-review.schema.json
      gate: .claude/context/history/gates/{{workflow_id}}/02-code-reviewer.json
    on_failure: 'Return to implementation step with feedback'
    description: |
      Review quick fix implementation for quality, security, and codebase impact:
      - Verify fix addresses the issue correctly
      - Check for unintended side effects
      - Review security implications
      - Ensure code quality standards maintained
      - Validate test coverage

  - step: 3
    name: 'Quality Validation'
    agent: qa
    inputs:
      - plan-{{workflow_id}}.json (from step 0)
      - dev-manifest.json (from step 1)
      - code-review-{{workflow_id}}.json (from step 2)
      - code-artifacts (from step 1)
    outputs:
      - quality-report.json
      - test-results.json
      - reasoning: .claude/context/history/reasoning/{{workflow_id}}/03-qa.json
    validation:
      schema: .claude/schemas/quality-report.schema.json
      gate: .claude/context/history/gates/{{workflow_id}}/03-qa.json
    secondary_outputs:
      - artifact: test-results.json
        schema: .claude/schemas/test-results.schema.json

  - step: 4
    name: 'QA Signoff'
    agent: qa
    inputs:
      - plan-{{workflow_id}}.json (from step 0)
      - quality-report.json (from step 3)
      - test-results.json (from step 3)
      - code-review-{{workflow_id}}.json (from step 2)
      - security-review-{{workflow_id}}.json (from step 1.5, optional)
    outputs:
      - qa-signoff-{{workflow_id}}.json
      - reasoning: .claude/context/history/reasoning/{{workflow_id}}/04-qa.json
    validation:
      schema: .claude/schemas/qa-signoff.schema.json
      gate: .claude/context/history/gates/{{workflow_id}}/04-qa.json
    description: |
      Final quality signoff for quick fix:
      - Review test results and quality metrics
      - Verify no regressions introduced
      - Confirm security review passed (if applicable)
      - Validate fix addresses original issue
      - Sign off on quality for merge
      - Block merge if quality gates not met

  - step: 4.5
    name: 'Publish Artifacts'
    agent: orchestrator
    skill: artifact-publisher
    condition: "validation_status == 'pass'"
    inputs:
      - artifact-registry.json
    policy: auto-on-pass
    validation:
      schema: .claude/schemas/artifact-registry.schema.json
    retry:
      max_attempts: 3
      on_failure: log_and_continue

completion_criteria:
  - Implementation validated against requirements
  - Tests passing
  - Code quality acceptable
  - No critical security issues

triggers:
  keywords:
    - bug fix
    - hotfix
    - quick fix
    - small feature
    - documentation
    - refactor
    - minor change
  file_changes: <5
  estimated_time: <4 hours

skip_agents:
  - analyst
  - pm
  - ux-expert
  - architect
